### PR TITLE
Added CSS for Image Submission

### PR DESCRIPTION
**Pull request by TRMoosee**
Prettified the submission text somewhat
can still be improved upon immensely, but this should act as a more pleasing placeholder for the time being

added styling above the html implementation, at a later date it would be preferable to put everything into an external stylesheet.

### CODE REVIEW

**Review by etekweb — COMMENTED** [review]
Would advise using classes instead of ids when you need to style something in multiple places (up button and down button could have upload_button class instead of id)

**Comment by TRMoosee** [comment]
Updated with classes instead of ids, changed around the styling a bit, added text instead of symbols.

Couldn't figure out why I couldn't use something I just created in base.css, might be on my end.

**Comment by cjvidro** [comment]
> Updated with classes instead of ids, changed around the styling a bit, added text instead of symbols.
> 
> Couldn't figure out why I couldn't use something I just created in base.css, might be on my end.

I'm not sure the specific issue you faced, but I've ran into this a few times when something in a CSS file wouldn't work:
Recall CSS ==> Cascading Style Sheet. Keyword cascading. Likely whatever you created has lower priority according to the CSS magic rules (aka [this](https://blog.logrocket.com/how-css-works-understanding-the-cascade-d181cd89a4d8)). Usually adding a `!important` or being more specific helps out. 

Could have just been you needed to restart the server (that's usually a back-end thing though, but it has happened to me on the front end too if I accidentally pause the terminal or something).

**Comment by TRMoosee** [comment]
Looks like adding !important worked for me

**Comment by etekweb** [comment]
@TRMoosee 
Yeah, this is needed because Bootstrap (the layout system in this project) uses !important in their internal CSS files, so their code overrides ours for certain things. That sort of out-of-order behavior is why using !important is generally discouraged, and one of the several reasons I avoid using Bootstrap in new projects. Unfortunately we are kinda stuck with Bootstrap at this point, so using !important to fix CSS issues is fine for this, just only where it is necessary.

**Review by cjvidro — APPROVED** [review]

**Pull request merged**
