### PR TITLE
Charles emails null fix

### PR DESCRIPTION
**Pull request by cjvidro**
˅˅˅˅˅˅˅˅˅˅˅˅˅˅˅˅˅˅˅˅˅˅˅˅˅˅˅˅
**THE DATABASE HAS BEEN CLEARED**
^^^^^^^^^^^^^^^^^^^^^^^^

Not sure if this was a cause of my doings or dev, but I noticed the DB was empty. If that wasn't intentional by someone, just copy in my simple change in the catalog views portion.

### CODE REVIEW

**Review by codetheweb — CHANGES_REQUESTED** [review]
Why was `.env-example` removed?

**Comment by codetheweb** [comment]
> Not sure if this was a cause of my doings or dev, but I noticed the DB was empty.

I deleted the local database in one of my PRs; generally speaking we shouldn't be committing that kind of stuff. I can add it back if we really want it, but I suspect that was the root cause of the migration issues that we talked about before. A better solution would be to write a script that seeded a local database with static data.

**Comment by cjvidro** [comment]
> Why was `.env-example` removed?

@codetheweb Are we not using your `.env` over `.env-example`? Perhaps I should have kept `.env-example` in the repo. Adding back in.

**Comment by codetheweb** [comment]
> @codetheweb Are we not using your .env over .env-example? Perhaps I should have kept .env-example in the repo. Adding back in.

The intention was to document all required environment variables somewhere in the repo. It could be in a .md file instead, just seemed convenient to put it there.

**Review by codetheweb — APPROVED** [review]

**Pull request merged**
